title: Marcin Dzieszkowski # your name (or website title) here
logo: "/images/15823084_1818661428406992_641875321320777882_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>

  <br><br>
  <a href="https://www.linkedin.com/in/marcin-dzieszkowski/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
